/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author roble
 */
public class FrmInventario extends javax.swing.JFrame {
    
    int idPresentacionSeleccionada = 0;
    int idInventarioSeleccionado = 0;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmInventario.class.getName());

    /**
     * Creates new form FrmInventario
     */
    public FrmInventario() {
        initComponents();

// PRUEBA DE CONEXIÓN TEMPORAL
modelo.Conexion testCon = new modelo.Conexion();
if(testCon.getConnection() != null) {
    System.out.println("¡CONEXIÓN EXITOSA A DOCKER!");
}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Tabs = new javax.swing.JTabbedPane();
        InventarioTab = new javax.swing.JPanel();
        EnvoltorioInventario = new javax.swing.JPanel();
        InventarioMedicamento = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtMedicamento = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtStock = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbxDistribucion = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cbxPresentacion = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtMinimo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtVencimiento = new javax.swing.JTextField();
        InventarioBotones = new javax.swing.JPanel();
        InventarioNuevo = new javax.swing.JButton();
        InventarioGuardar = new javax.swing.JButton();
        InventarioModificar = new javax.swing.JButton();
        InventarioEliminar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblInventario = new javax.swing.JTable();
        PresentasionesTab = new javax.swing.JPanel();
        Presentacion = new javax.swing.JPanel();
        NombrePresentacionPanel = new javax.swing.JPanel();
        NombrePresentasionLabel = new javax.swing.JLabel();
        txtNombrePresentacion = new javax.swing.JTextField();
        PresentacionBotones = new javax.swing.JPanel();
        PresentacionNuevo = new javax.swing.JButton();
        PresentacionGuardar = new javax.swing.JButton();
        PresentacionModificar = new javax.swing.JButton();
        PresentacionEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPresentaciones = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Farmacia Hospital Dragón");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 722, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(133, 133, 133))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        Tabs.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        InventarioTab.setLayout(new java.awt.BorderLayout());

        EnvoltorioInventario.setLayout(new java.awt.BorderLayout());

        jLabel2.setText("Nombre del Medicamento:");

        txtMedicamento.setText("EJ: Paracetamol 500mg");
        txtMedicamento.addActionListener(this::txtMedicamentoActionPerformed);

        jLabel3.setText("Stock de Unidades:");

        txtStock.setText("Ej: 50");

        jLabel4.setText("Tipo de Distribucion:");

        cbxDistribucion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Libre", "Receta" }));
        cbxDistribucion.addActionListener(this::cbxDistribucionActionPerformed);

        jLabel5.setText("Presentacion:");

        cbxPresentacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setText("Nivel Minimo:");

        txtMinimo.setText("Ej: 10");

        jLabel7.setText("Fecha de Vencimineto");

        txtVencimiento.setText("yyyy-mm-dd");

        javax.swing.GroupLayout InventarioMedicamentoLayout = new javax.swing.GroupLayout(InventarioMedicamento);
        InventarioMedicamento.setLayout(InventarioMedicamentoLayout);
        InventarioMedicamentoLayout.setHorizontalGroup(
            InventarioMedicamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InventarioMedicamentoLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(InventarioMedicamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(cbxDistribucion, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(170, 170, 170)
                .addGroup(InventarioMedicamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(cbxPresentacion, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(188, Short.MAX_VALUE))
        );
        InventarioMedicamentoLayout.setVerticalGroup(
            InventarioMedicamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InventarioMedicamentoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(InventarioMedicamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InventarioMedicamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbxPresentacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(InventarioMedicamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InventarioMedicamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(InventarioMedicamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InventarioMedicamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxDistribucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        EnvoltorioInventario.add(InventarioMedicamento, java.awt.BorderLayout.NORTH);

        InventarioNuevo.setBackground(new java.awt.Color(0, 153, 255));
        InventarioNuevo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        InventarioNuevo.setForeground(new java.awt.Color(255, 255, 255));
        InventarioNuevo.setText("Nuevo");
        InventarioNuevo.addActionListener(this::InventarioNuevoActionPerformed);

        InventarioGuardar.setBackground(new java.awt.Color(102, 204, 0));
        InventarioGuardar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        InventarioGuardar.setForeground(new java.awt.Color(255, 255, 255));
        InventarioGuardar.setText("Guardar");
        InventarioGuardar.addActionListener(this::InventarioGuardarActionPerformed);

        InventarioModificar.setBackground(new java.awt.Color(255, 204, 0));
        InventarioModificar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        InventarioModificar.setForeground(new java.awt.Color(255, 255, 255));
        InventarioModificar.setText("Modificar");
        InventarioModificar.addActionListener(this::InventarioModificarActionPerformed);

        InventarioEliminar.setBackground(new java.awt.Color(204, 0, 0));
        InventarioEliminar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        InventarioEliminar.setForeground(new java.awt.Color(255, 255, 255));
        InventarioEliminar.setText("Eliminar");
        InventarioEliminar.addActionListener(this::InventarioEliminarActionPerformed);

        javax.swing.GroupLayout InventarioBotonesLayout = new javax.swing.GroupLayout(InventarioBotones);
        InventarioBotones.setLayout(InventarioBotonesLayout);
        InventarioBotonesLayout.setHorizontalGroup(
            InventarioBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InventarioBotonesLayout.createSequentialGroup()
                .addContainerGap(228, Short.MAX_VALUE)
                .addComponent(InventarioNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(InventarioGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addComponent(InventarioModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(InventarioEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(179, 179, 179))
        );
        InventarioBotonesLayout.setVerticalGroup(
            InventarioBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InventarioBotonesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(InventarioBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InventarioNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InventarioGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InventarioModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InventarioEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        EnvoltorioInventario.add(InventarioBotones, java.awt.BorderLayout.SOUTH);

        InventarioTab.add(EnvoltorioInventario, java.awt.BorderLayout.NORTH);

        tblInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Medicamento", "Presentacion", "Stock", "Minimo", "Distribucion", "Vencimineto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblInventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblInventarioMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblInventario);

        InventarioTab.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        Tabs.addTab("Inventario", InventarioTab);

        PresentasionesTab.setLayout(new java.awt.BorderLayout());

        Presentacion.setLayout(new java.awt.BorderLayout());

        NombrePresentasionLabel.setText("Nombre de la Presentacion:");

        txtNombrePresentacion.setText("EJ: Jarabe");
        txtNombrePresentacion.addActionListener(this::txtNombrePresentacionActionPerformed);

        javax.swing.GroupLayout NombrePresentacionPanelLayout = new javax.swing.GroupLayout(NombrePresentacionPanel);
        NombrePresentacionPanel.setLayout(NombrePresentacionPanelLayout);
        NombrePresentacionPanelLayout.setHorizontalGroup(
            NombrePresentacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NombrePresentacionPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(NombrePresentacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NombrePresentasionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombrePresentacion, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(399, Short.MAX_VALUE))
        );
        NombrePresentacionPanelLayout.setVerticalGroup(
            NombrePresentacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NombrePresentacionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NombrePresentasionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombrePresentacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        Presentacion.add(NombrePresentacionPanel, java.awt.BorderLayout.NORTH);

        PresentacionNuevo.setBackground(new java.awt.Color(51, 153, 255));
        PresentacionNuevo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        PresentacionNuevo.setForeground(new java.awt.Color(255, 255, 255));
        PresentacionNuevo.setText("Nuevo");
        PresentacionNuevo.addActionListener(this::PresentacionNuevoActionPerformed);

        PresentacionGuardar.setBackground(new java.awt.Color(51, 204, 0));
        PresentacionGuardar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        PresentacionGuardar.setForeground(new java.awt.Color(255, 255, 255));
        PresentacionGuardar.setText("Guardar");
        PresentacionGuardar.addActionListener(this::PresentacionGuardarActionPerformed);

        PresentacionModificar.setBackground(new java.awt.Color(255, 204, 51));
        PresentacionModificar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        PresentacionModificar.setForeground(new java.awt.Color(255, 255, 255));
        PresentacionModificar.setText("Modificar");
        PresentacionModificar.addActionListener(this::PresentacionModificarActionPerformed);

        PresentacionEliminar.setBackground(new java.awt.Color(204, 0, 0));
        PresentacionEliminar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        PresentacionEliminar.setForeground(new java.awt.Color(255, 255, 255));
        PresentacionEliminar.setText("Eliminar");
        PresentacionEliminar.addActionListener(this::PresentacionEliminarActionPerformed);

        javax.swing.GroupLayout PresentacionBotonesLayout = new javax.swing.GroupLayout(PresentacionBotones);
        PresentacionBotones.setLayout(PresentacionBotonesLayout);
        PresentacionBotonesLayout.setHorizontalGroup(
            PresentacionBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PresentacionBotonesLayout.createSequentialGroup()
                .addContainerGap(217, Short.MAX_VALUE)
                .addComponent(PresentacionNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(PresentacionGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(PresentacionModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(PresentacionEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(194, 194, 194))
        );
        PresentacionBotonesLayout.setVerticalGroup(
            PresentacionBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PresentacionBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PresentacionBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PresentacionNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PresentacionGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PresentacionModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PresentacionEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Presentacion.add(PresentacionBotones, java.awt.BorderLayout.SOUTH);

        PresentasionesTab.add(Presentacion, java.awt.BorderLayout.NORTH);

        tblPresentaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Nombre de Presentacion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblPresentaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPresentacionesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPresentaciones);
        if (tblPresentaciones.getColumnModel().getColumnCount() > 0) {
            tblPresentaciones.getColumnModel().getColumn(0).setResizable(false);
        }

        PresentasionesTab.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        Tabs.addTab("Presentasiones", PresentasionesTab);

        getContentPane().add(Tabs, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMedicamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMedicamentoActionPerformed

    private void InventarioGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InventarioGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InventarioGuardarActionPerformed

    private void PresentacionGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PresentacionGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PresentacionGuardarActionPerformed

    private void tblPresentacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPresentacionesMouseClicked
        // TODO add your handling code here:
        // Obtenemos la fila a la que le dieron clic (empiezan en 0)
     int fila = tblPresentaciones.getSelectedRow();

     if (fila >= 0) {
         // Sacamos el ID (Columna 0) y el Nombre (Columna 1)
         idPresentacionSeleccionada = Integer.parseInt(tblPresentaciones.getValueAt(fila, 0).toString());
         String nombre = tblPresentaciones.getValueAt(fila, 1).toString();

         // Ponemos el nombre en la caja de texto para que lo puedan editar
         txtNombrePresentacion.setText(nombre);
     }
    }//GEN-LAST:event_tblPresentacionesMouseClicked

    private void PresentacionModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PresentacionModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PresentacionModificarActionPerformed

    private void PresentacionEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PresentacionEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PresentacionEliminarActionPerformed

    private void PresentacionNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PresentacionNuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PresentacionNuevoActionPerformed

    private void cbxDistribucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxDistribucionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxDistribucionActionPerformed

    private void InventarioNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InventarioNuevoActionPerformed
        // TODO add your handling code here:       
    }//GEN-LAST:event_InventarioNuevoActionPerformed

    private void tblInventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblInventarioMouseClicked
        // TODO add your handling code here:
        int fila = tblInventario.getSelectedRow();

     if (fila >= 0) {
         // Guardamos el ID en la variable global
         idInventarioSeleccionado = Integer.parseInt(tblInventario.getValueAt(fila, 0).toString());

         // Subimos los datos a las cajas de texto y combos
         txtMedicamento.setText(tblInventario.getValueAt(fila, 1).toString());
         cbxPresentacion.setSelectedItem(tblInventario.getValueAt(fila, 2).toString());
         txtStock.setText(tblInventario.getValueAt(fila, 3).toString());
         txtMinimo.setText(tblInventario.getValueAt(fila, 4).toString());
         cbxDistribucion.setSelectedItem(tblInventario.getValueAt(fila, 5).toString());
         txtVencimiento.setText(tblInventario.getValueAt(fila, 6).toString());
     }
    }//GEN-LAST:event_tblInventarioMouseClicked

    private void InventarioModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InventarioModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InventarioModificarActionPerformed

    private void InventarioEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InventarioEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InventarioEliminarActionPerformed

    private void txtNombrePresentacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombrePresentacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombrePresentacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmInventario().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel EnvoltorioInventario;
    private javax.swing.JPanel InventarioBotones;
    public javax.swing.JButton InventarioEliminar;
    public javax.swing.JButton InventarioGuardar;
    private javax.swing.JPanel InventarioMedicamento;
    public javax.swing.JButton InventarioModificar;
    public javax.swing.JButton InventarioNuevo;
    private javax.swing.JPanel InventarioTab;
    private javax.swing.JPanel NombrePresentacionPanel;
    private javax.swing.JLabel NombrePresentasionLabel;
    private javax.swing.JPanel Presentacion;
    private javax.swing.JPanel PresentacionBotones;
    public javax.swing.JButton PresentacionEliminar;
    public javax.swing.JButton PresentacionGuardar;
    public javax.swing.JButton PresentacionModificar;
    public javax.swing.JButton PresentacionNuevo;
    private javax.swing.JPanel PresentasionesTab;
    private javax.swing.JTabbedPane Tabs;
    public javax.swing.JComboBox<String> cbxDistribucion;
    public javax.swing.JComboBox<String> cbxPresentacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable tblInventario;
    public javax.swing.JTable tblPresentaciones;
    public javax.swing.JTextField txtMedicamento;
    public javax.swing.JTextField txtMinimo;
    public javax.swing.JTextField txtNombrePresentacion;
    public javax.swing.JTextField txtStock;
    public javax.swing.JTextField txtVencimiento;
    // End of variables declaration//GEN-END:variables
    public void resaltarStockBajo() {
    tblInventario.setDefaultRenderer(Object.class, new javax.swing.table.DefaultTableCellRenderer() {
        @Override
        public java.awt.Component getTableCellRendererComponent(javax.swing.JTable table, Object value,
                boolean isSelected, boolean hasFocus, int row, int column) {
            
            java.awt.Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
            
            // Obtenemos los valores de las columnas Stock (3) y Mínimo (4)
            int stock = Integer.parseInt(table.getValueAt(row, 3).toString());
            int minimo = Integer.parseInt(table.getValueAt(row, 4).toString());

            if (stock < minimo) {
                c.setBackground(java.awt.Color.RED);
                c.setForeground(java.awt.Color.WHITE); // Texto blanco para que se lea mejor
            } else {
                // Si el stock es normal, usamos colores por defecto
                c.setBackground(isSelected ? table.getSelectionBackground() : table.getBackground());
                c.setForeground(isSelected ? table.getSelectionForeground() : table.getForeground());
            }
            return c;
        }
    });
}
}
